### ISSUE TITLE
Box description could not be specified on the creation step

### ISSUE THREAD

**Issue by legal90** [nickcharlton/atlas-ruby#2]
When I use this way to create a new box version, it still has an empty description:

``` ruby
version = box.create_version(version: '1.0.0', description: 'My super box')
# or
version = box.create_version({version: '1.0.0', description: 'My super box'})
```

The only way I can do that is a double API call:

``` ruby
version = box.create_version(version: '1.0.0')
version.description = 'My super box'
version.save
```

Is it an expected behavior?

**Comment by nickcharlton** [comment]
Ah, hah. This looks like a bug, I can't see a [test](https://github.com/nickcharlton/atlas-ruby/blob/master/spec/box_spec.rb#L55) for assigning the description as well. I'll have a look at it.
